apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ms-process-video
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Hackathon-Fiap-202/ms-process-video
    targetRevision: main
    path: infra/k8s
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
